apiVersion: v1
kind: Service
metadata:
  name: drupal-mysql-service
  labels:
    app: drupal
    type: service
    data: mysql
spec:
  ports:
  - name: mysql
    port: 3306
  type: ClusterIP
  selector:
    app: drupal
    data: mysql