apiVersion: v1
kind: Service
metadata:
  name: drupal-mysql-service
  labels:
    app: drupal-mysql
    tier: backend
spec:
  ports:
  - name: mysql
    port: 3306
  type: ClusterIP
  selector:
    app: drupal-mysql