apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-pv
  labels:
    app: drupal
    type: data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
#  persistentVolumeReclaimPolicy:
  hostPath:
    path: /drupal-data
#    type: Directory