apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
  labels:
    app: pento
    type: data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
#  persistentVolumeReclaimPolicy:
  hostPath:
    path: /web
#    type: Directory