apiVersion: v1
kind: Service
metadata:
  name: gop-fs-service
  labels:
    app: fileserver
    data: frontend
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31200
  type: NodePort
  selector:
    app: drupal