apiVersion: v1
kind: Pod
metadata:
  name: gop-fileserver
  labels:
    app: fileserver
    data: frontend
spec:
  volumes:
    - name: data-store
      persistentVolumeClaim:
        claimName: data-pvc
  containers:
    - name: gop-fileserver
      image: kodekloud/fileserver
      ports:
        - containerPort: 8080
#          name: http-server
      volumeMounts:
        - mountPath: /web
          name: data-store