---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis01
  labels:
    app: pento
    type: data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
#  persistentVolumeReclaimPolicy:
  hostPath:
    path: /redis01
#    type: Directory

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis02
  labels:
    app: pento
    type: data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /redis02

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis03
  labels:
    app: pento
    type: data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /redis03

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis04
  labels:
    app: pento
    type: data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /redis04

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis05
  labels:
    app: pento
    type: data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /redis05

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis06
  labels:
    app: pento
    type: data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /redis06
